import { createRequire } from 'node:module'
import { existsSync, readFileSync } from 'node:fs'
import assert from 'node:assert/strict'
const require = createRequire(import.meta.url)
let playwright
try { playwright = require('playwright') } catch { playwright = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright') }
const executablePath = process.env.BROWSER_EXECUTABLE || ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync)
const browser = await playwright.chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}) })
const context = await browser.newContext({ acceptDownloads: true })
const base = process.env.DEMO_URL || 'http://127.0.0.1:5173'
const page = await context.newPage()
const errors = [], outside = []
context.on('page', p => p.on('pageerror', e => errors.push(e.message)))
page.on('pageerror', e => errors.push(e.message))
await context.route('**/*', route => { const url = route.request().url(); if (url.startsWith(base) || url.startsWith('blob:') || url.startsWith('data:')) return route.continue(); outside.push(url); return route.abort() })
const visible = async locator => { await locator.waitFor({ state: 'visible', timeout: 3000 }) }
async function fillReport(reporter) {
  await reporter.getByRole('button', { name: 'Covered', exact: true }).click()
  await reporter.getByRole('button', { name: 'Next', exact: true }).click()
  await reporter.getByRole('radio', { name: /Seme/, exact: false }).click()
  await reporter.getByRole('radio', { name: 'Benin', exact: true }).click()
  await reporter.getByRole('button', { name: 'Next', exact: true }).click()
  await reporter.getByRole('radio', { name: 'No', exact: false }).click()
  await reporter.getByLabel('What happened?').fill('Sample vehicle incident at the crossing. Illustrative details only.')
  await reporter.getByRole('button', { name: 'Review', exact: true }).click()
}
try {
  await page.goto(base)
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await page.getByRole('button', { name: 'Issue policy and allocate card', exact: true }).click()
  await visible(page.getByText('Recorded on the card register.', { exact: false }))
  assert.match(await page.getByTestId('allocated-card').textContent(), /NG-26-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]/)
  await page.getByRole('button', { name: 'Issued just now', exact: false }).first().click()
  await page.getByRole('button', { name: 'Verify card', exact: true }).click()
  await visible(page.getByText('Active policy, Brown Card recorded.', { exact: false }))
  for (const [sample, message] of [['Lapsed', 'A genuine card, but the policy has expired.'], ['Not found', 'No card on the register. Refer for inspection.'], ['Invalid', 'Not a valid Brown Card number.']]) {
    await page.getByRole('button', { name: sample, exact: false }).click()
    await page.getByRole('button', { name: 'Verify card', exact: true }).click()
    await visible(page.getByText(message, { exact: false }))
  }
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download quarterly return', exact: true }).click()
  const download = await downloadPromise
  assert.equal(download.suggestedFilename(), 'quarterly_return.csv')
  const csv = readFileSync(await download.path(), 'utf8')
  assert.equal(csv.trim().split(/\r?\n/).length, 13)
  assert.match(csv, /Insurer A/); assert.match(csv, /Insurer L/)
  await page.getByRole('button', { name: 'Covered', exact: true }).click()
  await page.getByRole('button', { name: 'Verify card', exact: true }).click()
  await page.getByRole('button', { name: 'End', exact: true }).click()
  await page.waitForTimeout(500)
  assert.match(await page.getByTestId('ussd-screen').textContent(), /Dial/)
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  assert.equal(await page.getByLabel('Policyholder', { exact: true }).inputValue(), 'Sample holder')
  assert.doesNotMatch(await page.getByTestId('allocated-card').textContent(), /NG-26-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]/)
  assert.equal(await page.getByRole('button', { name: 'Issued just now', exact: true }).count(), 0)
  console.log('PASS: card issuance, all short-code statuses, 12-insurer CSV, reset, stale-reply protection')
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await page.getByRole('button', { name: /Compliance console/ }).click()
  assert.equal(await page.locator('section[aria-labelledby="compliance-headline"] p[aria-live]').textContent(), '93.4%')
  await page.getByRole('combobox').first().selectOption('A')
  const rows = page.locator('table').first().locator('tbody tr')
  assert.ok(await rows.count() > 0)
  for (const row of await rows.all()) assert.match(await row.textContent(), /Insurer A/)
  await page.getByRole('checkbox', { name: 'Select all open batches in view', exact: true }).check()
  await page.getByRole('button', { name: 'Remind', exact: true }).click()
  await visible(page.getByText(/Reminder sent for/))
  assert.equal(await page.locator('section[aria-labelledby="compliance-headline"] p[aria-live]').textContent(), '93.4%')
  await page.getByRole('checkbox', { name: 'Select all open batches in view', exact: true }).check()
  await page.getByRole('button', { name: 'Assign', exact: true }).click()
  await visible(page.getByText(/Assigned .* batches/))
  await page.getByRole('checkbox', { name: 'Select all open batches in view', exact: true }).check()
  await page.getByRole('button', { name: 'Back-fill', exact: true }).click()
  await visible(page.getByText(/Cleared .* policies/))
  assert.ok(parseFloat(await page.locator('section[aria-labelledby="compliance-headline"] p[aria-live]').textContent()) > 93.4)
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await page.getByRole('button', { name: /Compliance console/ }).click()
  assert.equal(await page.locator('section[aria-labelledby="compliance-headline"] p[aria-live]').textContent(), '93.4%')
  console.log('PASS: compliance baseline, filters, reminders, assignment, back-fill, reset')
  const dashboard = await context.newPage(), reporter = await context.newPage()
  await dashboard.goto(`${base}/?view=claims`)
  await reporter.goto(`${base}/?view=reporter`)
  await fillReport(reporter)
  const started = Date.now()
  await reporter.getByRole('button', { name: 'Send report', exact: true }).click()
  await visible(reporter.getByRole('heading', { name: 'Report received' }))
  const ref = await reporter.getByText(/^CL-\d{4}$/).first().textContent()
  await visible(dashboard.getByText(ref, { exact: true }).first())
  assert.ok(Date.now() - started < 3000, 'Report-to-dashboard must complete in under 3 seconds')
  console.log(`PASS: cross-window report arrival in ${Date.now() - started}ms`)
  await context.setOffline(true)
  await page.getByRole('checkbox', { name: 'Select all open batches in view', exact: true }).check()
  await page.getByRole('button', { name: 'Back-fill', exact: true }).click()
  await visible(page.getByText(/Cleared .* policies/))
  await reporter.getByRole('button', { name: 'Start another report', exact: true }).click()
  await fillReport(reporter)
  await reporter.getByRole('button', { name: 'Save and send when online', exact: true }).click()
  await visible(reporter.getByRole('heading', { name: 'Saved on this phone', exact: true }))
  await context.setOffline(false)
  await visible(reporter.getByRole('heading', { name: 'Report received', exact: true }))
  console.log('PASS: offline actions and queued report reconnect')
  for (const p of [page, reporter, dashboard]) await visible(p.getByText(/Illustrative data/).first())
  assert.deepEqual(outside, [], 'All assets and operations must use the local origin')
  assert.deepEqual(errors, [], 'No browser exceptions')
} finally { await browser.close() }


